// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cnt_grpc.proto

/*
Package cnt is a generated protocol buffer package.

It is generated from these files:
	cnt_grpc.proto

It has these top-level messages:
	CntRq
	CntRp
*/
package cnt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 请求
type CntRq struct {
	Num int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *CntRq) Reset()                    { *m = CntRq{} }
func (m *CntRq) String() string            { return proto.CompactTextString(m) }
func (*CntRq) ProtoMessage()               {}
func (*CntRq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CntRq) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// 响应
type CntRp struct {
	Num int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *CntRp) Reset()                    { *m = CntRp{} }
func (m *CntRp) String() string            { return proto.CompactTextString(m) }
func (*CntRp) ProtoMessage()               {}
func (*CntRp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CntRp) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*CntRq)(nil), "cnt.CntRq")
	proto.RegisterType((*CntRp)(nil), "cnt.CntRp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Counter service

type CounterClient interface {
	// 计数器自增
	// @num:需要增加的计数值
	Add(ctx context.Context, in *CntRq, opts ...grpc.CallOption) (*CntRp, error)
	// 计数器自减
	// @num:需要减少的计数值
	Sub(ctx context.Context, in *CntRq, opts ...grpc.CallOption) (*CntRp, error)
	// 计数器值获取
	// @return: num
	Get(ctx context.Context, in *CntRq, opts ...grpc.CallOption) (*CntRp, error)
}

type counterClient struct {
	cc *grpc.ClientConn
}

func NewCounterClient(cc *grpc.ClientConn) CounterClient {
	return &counterClient{cc}
}

func (c *counterClient) Add(ctx context.Context, in *CntRq, opts ...grpc.CallOption) (*CntRp, error) {
	out := new(CntRp)
	err := grpc.Invoke(ctx, "/cnt.Counter/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) Sub(ctx context.Context, in *CntRq, opts ...grpc.CallOption) (*CntRp, error) {
	out := new(CntRp)
	err := grpc.Invoke(ctx, "/cnt.Counter/Sub", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) Get(ctx context.Context, in *CntRq, opts ...grpc.CallOption) (*CntRp, error) {
	out := new(CntRp)
	err := grpc.Invoke(ctx, "/cnt.Counter/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Counter service

type CounterServer interface {
	// 计数器自增
	// @num:需要增加的计数值
	Add(context.Context, *CntRq) (*CntRp, error)
	// 计数器自减
	// @num:需要减少的计数值
	Sub(context.Context, *CntRq) (*CntRp, error)
	// 计数器值获取
	// @return: num
	Get(context.Context, *CntRq) (*CntRp, error)
}

func RegisterCounterServer(s *grpc.Server, srv CounterServer) {
	s.RegisterService(&_Counter_serviceDesc, srv)
}

func _Counter_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CntRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cnt.Counter/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).Add(ctx, req.(*CntRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CntRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cnt.Counter/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).Sub(ctx, req.(*CntRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CntRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cnt.Counter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).Get(ctx, req.(*CntRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Counter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cnt.Counter",
	HandlerType: (*CounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Counter_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _Counter_Sub_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Counter_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cnt_grpc.proto",
}

func init() { proto.RegisterFile("cnt_grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0x2b, 0x89,
	0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0xce, 0x2b, 0x51,
	0x92, 0xe4, 0x62, 0x75, 0xce, 0x2b, 0x09, 0x2a, 0x14, 0x12, 0xe0, 0x62, 0xce, 0x2b, 0xcd, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0x61, 0x52, 0x05, 0x98, 0x52, 0x46, 0x69, 0x5c,
	0xec, 0xce, 0xf9, 0xa5, 0x79, 0x25, 0xa9, 0x45, 0x42, 0xb2, 0x5c, 0xcc, 0x8e, 0x29, 0x29, 0x42,
	0x5c, 0x7a, 0xc9, 0x79, 0x25, 0x7a, 0x60, 0xa3, 0xa4, 0x10, 0xec, 0x02, 0x90, 0x74, 0x70, 0x69,
	0x12, 0x3e, 0x69, 0xf7, 0xd4, 0x12, 0x5c, 0xd2, 0x49, 0x6c, 0x60, 0x97, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xe4, 0x55, 0x98, 0x23, 0xbb, 0x00, 0x00, 0x00,
}
